# Generated by Django 2.2.24 on 2023-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230329_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_flats',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
