# Generated by Django 2.2.24 on 2023-03-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
    ]
